
#
# This LookML file was generated by AtScale on 2024-09-20T18:37:13.459904364Z
#
# AtScale version: C2024.1.0
# Catalog: AtScale Finance_daniel_test

connection: "daniel-atscale-finance"
label: "AtScale Finance_daniel_test"


include: "/views/AtScale_Finance__daniel__test/AtScale__Finance.view.lkml"

include: "/views/AtScale_Finance__daniel__test/SNF_Usage_History__Cube.view.lkml"

include: "/views/AtScale_Finance__daniel__test/AtScale__RevenueOperations.view.lkml"

include: "/views/AtScale_Finance__daniel__test/GCPUsage.view.lkml"

include: "/views/AtScale_Finance__daniel__test/Customer__Utilization.view.lkml"


explore: AtScale_Finance {
  label: "AtScale_Finance"
}

explore: SNF_Usage_History__Cube {
  label: "SNF Usage History  Cube"
}

explore: AtScale_RevenueOperations {
  label: "AtScale_RevenueOperations"
}

explore: GCPUsage {
  label: "GCPUsage"
}

explore: Customer_Utilization {
  label: "Customer_Utilization"
}

